
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trades?createDatabaseIfNotExist=true&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: 123
  sql:
    init:
      mode: always  #dont need for embedded database, it turns on automatically
  jpa:    
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true 
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 5
          batch_versioned_data: true

logging:
  level:
    org.hibernate.engine.jdbc.batch: DEBUG